name: uni-sadp-bundle
version: v1beta
type: bundle
tags:
  - dataproduct
description: This bundle resource is for the Units SADP.
layer: "user"
bundle:
  resources:
    - id: quality_purchase
      file: C:\Users\Manoj\Desktop\customer-behavior-training\deployment\units.yml
      workspace: public