name: cub-sadp-spec
version: v1beta
entity: product
type: data
tags:
  - DPUsecase.Obsolescence
  - DPTier.Source Aligned
description: This is a source aligned data procuct for customer unit bridge.
refs:
  - title: 'Workspace Info'
    href: https://dataos.info/interfaces/cli/command_reference/#workspace
  
v1beta:
  data:
    meta:
      title: Customer Unit Bridge
      sourceCodeUrl: https://github.com/Acies-Manoj/ObsolescenceDP
    collaborators:
      - name: vigneshadhikesavan
        description: owner
    
    resource:
      refType: dataos
      ref: bundle:v1beta:cub-sadp-bundle

    inputs:
      - refType: dataos
        ref: dataset:TRAINING_OBS:SAMPLE_MANOJ:CONTRACT_UNIT_BRIDGE

      