name: cub-sadp-bundle
version: v1beta
type: bundle
tags:
  - dataproduct
description: This bundle resource is for the Contract Unit Bridge SADP.
layer: "user"
bundle:
  resources:
    - id: quality_contract_unit_bridge
      file: C:\Users\Manoj\Desktop\ObsolescenceDP\SADPs\QCs\contract_unit_bridge.yml
      workspace: public