name: opp-sadp-spec
version: v1beta
entity: product
type: data
tags:
  - DPUsecase.Obsolescence
  - DPTier.Source Aligned
description: This is a source aligned data procuct for Opportunity.
refs:
  - title: 'Workspace Info'
    href: https://dataos.info/interfaces/cli/command_reference/#workspace

v1beta:
  data:
    meta:
      title: Opportunity
      sourceCodeUrl: https://github.com/Acies-Manoj/ObsolescenceDP
    collaborators:
      - name: vigneshadhikesavan
        description: owner
    
    resource:
      refType: dataos
      ref: bundle:v1beta:opp-sadp-bundle

    inputs:
      - refType: dataos
        ref: dataset:TRAINING_OBS:SAMPLE_MANOJ:OPPORTUNITY_UNIT

      