name: opp-sadp-bundle
version: v1beta
type: bundle
tags:
  - dataproduct
description: This bundle resource is for the Opportunity SADP.
layer: "user"
bundle:
  resources:
    - id: quality_opportunity
      file: C:\Users\Manoj\Desktop\customer-behavior-training\deployment\opportunity_unit.yml
      workspace: public