name: coma-sadp-spec
version: v1beta
entity: product
type: data
tags:
  - DPUsecase.Obsolescence
  - DPTier.Source Aligned
description: This is a source aligned data procuct for customer ont margin agg.
refs:
  - title: 'Workspace Info'
    href: https://dataos.info/interfaces/cli/command_reference/#workspace

v1beta:
  data:
    meta:
      title: Customer ONT Margin Aggregation
      sourceCodeUrl: https://github.com/Acies-Manoj/ObsolescenceDP

    collaborators:
      - name: vigneshadhikesavan
        description: owner
    
    resource:
      refType: dataos
      ref: bundle:v1beta:coma-dp-bundle

    inputs:
      - refType: dataos
        ref: dataset:TRAINING_OBS:SAMPLE_MANOJ:CONTRACT_ONT_MARGIN_AGG

