name: bui-sadp-bundle
version: v1beta
type: bundle
tags:
  - dataproduct
description: This bundle resource is for the Buildings SADP.
layer: "user"
bundle:
  resources:
    - id: quality_purchase
      file: C:\Users\Manoj\Desktop\ObsolescenceDP\SADPs\QCs\buildings.yml
      workspace: public